# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghaw < Formula
  desc "Terminal TUI for monitoring GitHub Actions workflow runs"
  homepage "https://github.com/dzoba/github-actions-watcher"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v2.0.1/github-actions-watcher_darwin_amd64.tar.gz"
      sha256 "b08a63e74bddf2b9b7295a47a1329d21729fd7e6c757dea425d8e3965eb876e6"

      def install
        bin.install "ghaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v2.0.1/github-actions-watcher_darwin_arm64.tar.gz"
      sha256 "d757e2103438c237cf4a5c6a65f6a8d5927d06b200000a5a0017d5fd3e8a3646"

      def install
        bin.install "ghaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v2.0.1/github-actions-watcher_linux_amd64.tar.gz"
      sha256 "75bfe7b83540856a176f32d0d677f7d2888e4d66bae514726953f6e1610d2788"
      def install
        bin.install "ghaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v2.0.1/github-actions-watcher_linux_arm64.tar.gz"
      sha256 "047f22bdee05b633f725b47477983a2e15f8eae7835d5e5d0aee03c8782ad309"
      def install
        bin.install "ghaw"
      end
    end
  end
end
