# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubActionsWatcher < Formula
  desc "Terminal TUI for monitoring GitHub Actions workflow runs"
  homepage "https://github.com/dzoba/github-actions-watcher"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v1.0.0/github-actions-watcher_darwin_amd64.tar.gz"
      sha256 "15ab82fcd4a4431e55f070ead6433fbdf374ebe367599f23176b4c6d2385fc60"

      def install
        bin.install "ghaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v1.0.0/github-actions-watcher_darwin_arm64.tar.gz"
      sha256 "d7f40b02dd34922738e95e36a49e714f6906d53d93ef124ec1ab63228d2ddd52"

      def install
        bin.install "ghaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v1.0.0/github-actions-watcher_linux_amd64.tar.gz"
      sha256 "64dcd243afe071476b0b331d03a767f31e1e23c588a03164e14b766b9dbf2704"
      def install
        bin.install "ghaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dzoba/github-actions-watcher/releases/download/v1.0.0/github-actions-watcher_linux_arm64.tar.gz"
      sha256 "e5686126eb25938ee9daf6d59c74217c2119540a3e217293cc4c6f1ac19eab52"
      def install
        bin.install "ghaw"
      end
    end
  end
end
